/* admin_telegram_v6.js (short) */
(function(){
  function qs(s, el){ return (el||document).querySelector(s); }
  function val(s){ var el=qs(s); return el ? (el.value||'').trim() : ''; }
  function setV(s,v){ var el=qs(s); if(el) el.value=v||''; }
  function setC(s,on){ var el=qs(s); if(el) el.checked=!!(on===true||on==='1'||on===1||on==='true'); }
  function toast(t,cls){ var c=qs('#toasts'); if(!c) return; var d=document.createElement('div'); d.className='toast '+(cls||'info'); d.textContent=t; c.appendChild(d); setTimeout(function(){d.remove();},3800);}
  function api(a,data,method){ method=method||(data?'POST':'GET'); var fd=null; if(data){ fd=new FormData(); Object.keys(data).forEach(function(k){fd.append(k,data[k]);}); }
    var meta=document.querySelector('meta[name="csrf-token"]'); var hdr={}; if(meta&&meta.content) hdr['X-CSRF-Token']=meta.content;
    return fetch('admin_api_telegram.php?action='+encodeURIComponent(a), {method:method, body:fd, headers:hdr, credentials:'same-origin'}).then(function(r){return r.json();}); }
  function render(j){ if(j&&j.data){ setV('#tgToken',''); setV('#tgAdminChat', j.data.admin_chat||''); setC('#tgNotifySave', j.data.notify_save); setC('#tgNotifyLogins', j.data.notify_logins); setC('#tgNotifyUsers', j.data.notify_users); setC('#tgNotifyErrors', j.data.notify_errors); setV('#tgSecret', j.data.secret||''); var sc=qs('#tgSubsCount'); if(sc) sc.textContent=String(j.data.subs_count||0); } var m=qs('#tgBotMeta'); if(m){ var parts=[]; if(j&&j.bot&&typeof j.bot.ok!=='undefined') parts.push(j.bot.ok?'Бот: активен':'Бот: не активен'); if(j&&j.webhook&&typeof j.webhook.ok!=='undefined'){ var w=j.webhook.result||j.webhook; parts.push((w&&w.url)?'Webhook: установлен':'Webhook: не установлен'); } if(j&&j.data&&j.data.has_token) parts.push('Токен: …'+(j.data.token_tail||'')); if(j&&j.data) parts.push('Подписчики: '+(j.data.subs_count||0)); m.textContent=parts.join(' · ');} }
  function load(){ if(!qs('#tgPane')) return; api('get').then(function(j){ if(j.ok===false){toast(j.error||'Ошибка','err'); return;} render(j); }).catch(function(){toast('Ошибка запроса','err');}); }
  function save(setHook){ var payload={token:val('#tgToken'), admin_chat:val('#tgAdminChat'),
    notify_save: qs('#tgNotifySave')&&qs('#tgNotifySave').checked?'1':'0',
    notify_logins: qs('#tgNotifyLogins')&&qs('#tgNotifyLogins').checked?'1':'0',
    notify_users: qs('#tgNotifyUsers')&&qs('#tgNotifyUsers').checked?'1':'0',
    notify_errors: qs('#tgNotifyErrors')&&qs('#tgNotifyErrors').checked?'1':'0'};
    api('save', payload, 'POST').then(function(j){ if(j.ok===false){toast(j.error||'Не удалось сохранить','err'); return;} if(setHook){ api('webhook_set', null, 'POST').then(function(x){ if(x.ok===false){toast(x.error||'Webhook не установлен','err'); load(); return;} toast('Сохранено и webhook установлен','ok'); load(); }); } else { toast('Сохранено','ok'); load(); } }); }
  function sendTest(){ var t=val('#tgTestText')||'Проверка связи с ботом.'; api('send_test',{text:t},'POST').then(function(j){ if(j.ok===false){toast(j.error||'Тест не отправлен','err'); return;} toast('Сообщение отправлено','ok'); }); }
  function regenSecret(){ api('regenerate_secret',null,'POST').then(function(j){ if(j.ok===false){toast(j.error||'Ошибка','err'); return;} setV('#tgSecret', j.secret||''); toast('Секрет обновлён','ok'); });}
  function setHook(){ api('webhook_set',null,'POST').then(function(j){ toast(j.ok===false?(j.error||'Ошибка'):'Webhook установлен', j.ok===false?'err':'ok'); load(); });}
  function delHook(){ api('webhook_delete',null,'POST').then(function(j){ toast(j.ok===false?(j.error||'Ошибка'):'Webhook снят', j.ok===false?'err':'ok'); load(); });}
  function infoHook(){ api('webhook_info').then(function(j){ var url=(j.webhook&&(j.webhook.result&&j.webhook.result.url||j.webhook.url))||'нет'; toast('Webhook: '+url,'info'); });}
  function toggleSubs(){ var box=qs('#tgSubsList'); if(!box) return; if(box.style.display==='none'||box.style.display===''){ api('subscribers').then(function(j){ if(j.ok===false){toast(j.error||'Ошибка','err'); return;} var h='<table class="table"><thead><tr><th>Chat</th><th>Имя</th><th>Тип</th><th>Админ</th><th>Активность</th></tr></thead><tbody>'; (j.items||[]).forEach(function(s){ var name=(s.title||(s.first_name||'')+' '+(s.last_name||'')).trim(); h+='<tr><td>'+(s.chat_id||'')+'</td><td>'+(name||'—')+'</td><td>'+(s.type||'')+'</td><td>'+(s.is_admin?'да':'нет')+'</td><td>'+(s.last_seen_at||'')+'</td></tr>';}); h+='</tbody></table>'; box.innerHTML=h; box.style.display='block'; var sc=qs('#tgSubsCount'); if(sc) sc.textContent=String(j.count||0); }); } else { box.style.display='none'; } }
  document.addEventListener('DOMContentLoaded', function(){ if(!qs('#tgPane')) return; qs('#tgSaveBtn')&&qs('#tgSaveBtn').addEventListener('click',function(e){e.preventDefault();save(false);}); qs('#tgSaveAndHookBtn')&&qs('#tgSaveAndHookBtn').addEventListener('click',function(e){e.preventDefault();save(true);}); qs('#tgSetHookBtn')&&qs('#tgSetHookBtn').addEventListener('click',function(e){e.preventDefault();setHook();}); qs('#tgDelHookBtn')&&qs('#tgDelHookBtn').addEventListener('click',function(e){e.preventDefault();delHook();}); qs('#tgInfoHookBtn')&&qs('#tgInfoHookBtn').addEventListener('click',function(e){e.preventDefault();infoHook();}); qs('#tgRegenSecretBtn')&&qs('#tgRegenSecretBtn').addEventListener('click',function(e){e.preventDefault();regenSecret();}); qs('#tgTestBtn')&&qs('#tgTestBtn').addEventListener('click',function(e){e.preventDefault();sendTest();}); qs('#tgLoadSubsBtn')&&qs('#tgLoadSubsBtn').addEventListener('click',function(e){e.preventDefault();toggleSubs();}); load(); }); })();
