USE bereg_db;

CREATE TABLE IF NOT EXISTS telegram_settings (
  id TINYINT PRIMARY KEY,
  token VARCHAR(128) NOT NULL DEFAULT '',
  admin_chat VARCHAR(64) NOT NULL DEFAULT '',
  secret VARCHAR(64) NOT NULL DEFAULT '',
  notify_save TINYINT(1) NOT NULL DEFAULT 1,
  notify_logins TINYINT(1) NOT NULL DEFAULT 1,
  notify_users TINYINT(1) NOT NULL DEFAULT 1,
  notify_errors TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO telegram_settings (id, secret)
SELECT 1, SUBSTRING(MD5(RAND()),1,32)
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM telegram_settings WHERE id = 1);

CREATE TABLE IF NOT EXISTS tg_subscribers (
  chat_id BIGINT PRIMARY KEY,
  type VARCHAR(20) NULL,
  username VARCHAR(64) NULL,
  first_name VARCHAR(64) NULL,
  last_name VARCHAR(64) NULL,
  title VARCHAR(128) NULL,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  last_seen_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
